### PR TITLE
bumping minimum php version to 5.5

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by Maks3w** [comment]
This is not justified

**Comment by samsonasik** [comment]
why?

**Comment by Maks3w** [comment]
Code is compatible with 5.3 there is no reason for change the version constraint

**Comment by samsonasik** [comment]
compatible with 5.3.3 too ? Last time, we change 5.3.3 to 5.3.23 in all
components dramatically...

Warm Regards,

Abdul Malik Ikhsan

2015-06-04 13:51 GMT+07:00 Maks3w notifications@github.com:

**Comment by weierophinney** [comment]
This perfectly justified; our `.travis.yml` indicates we only test from 5.5 forwards; this is just making the `composer.json` consistent with what we test.

**Pull request merged**
